version: 2

updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
    labels:
      - dependabot
      - dependencies
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - dependabot
      - dependencies
