name: 'Dependabot Changelog'
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - labeled
      - unlabeled

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: dangoslen/dependabot-changelog-helper@v4
        with:
          activationLabel: 'dependabot'
          sort: alpha
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Changelog"
